### ISSUE TITLE
Add mappings to source maps

### ISSUE THREAD

**Issue by TienSFU25** [Microsoft/sourcemap-toolkit#49]
We're looking to (manually) generate source maps as part of our build process. Are there plans to support adding mappings to the SourceMap?

**Comment by christiang88** [comment]
Can you clarify what functionality is missing? `SourceMapGenerator` takes a `SourceMap` object and serializes it into JSON. If you add a `MappingEntry` to the `ParsedMappings` list on a `SourceMap` object, it should appear in the serialized output.

**Comment by TienSFU25** [comment]
Yes that's right. It is possible to manually add source line/columns and generated line/columns to the `SourceMap` and generate a map file.

**Comment by TienSFU25** [comment]
Have you thought of adding functionality for nested source maps? It would be useful for tracing source maps all the way back to their source.

**Comment by christiang88** [comment]
I'll close this issue since it is already supported by the API. With regards to source map composition, please open a new issue with details on the scenario you are trying to address and the API changes you would like to see.
