### ISSUE TITLE
Source map composition

### ISSUE THREAD

**Issue by TienSFU25** [Microsoft/sourcemap-toolkit#50]
My use case is this:

We start with three Typescript files: `a.ts`, `b.t`s and `c.ts`

Typescript converts these into javascript files, respectively: `a.js`, `b.js` and `c.js`.

At build time, we do additional transformations. Lets assume we concat `a.js` and `b.js`, so now we have:

`ab.js`, `c.js`

At runtime, we do additional transformations and serve the file `abc.js`

Assuming all the intermediate javascript files have corresponding map files, we would like a map file from `abc.js` to the original Typescript files. This would be very helpful for development.

**Comment by christiang88** [comment]
So there aren't any active plans for us to implement this in the near future. However, this is something that would be valuable to include in the toolkit. We accept pull requests if you decide to take this on.

**Comment by TienSFU25** [comment]
Ok, I would be interested in contributing. Let me come up with a prototype that you can take a look at and we can go from there.

**Comment by christiang88** [comment]
Resolved with #52 . NuGet package version 1.0.29 contains this change.
