### ISSUE TITLE
Line based GetMappingEntryForGeneratedSourcePosition

### ISSUE THREAD

**Issue by TienSFU25** [Microsoft/sourcemap-toolkit#54]
Source maps not based on Javascript parsing (for example: bundling files) may not have column information. To support lookups for these lossy maps, can we add an overload or fallback to lines when columns do not match?

**Comment by christiang88** [comment]
Was this resolved with #55, or is this another issue? If it is different, can you add more details?

**Comment by TienSFU25** [comment]
yeah this can be closed. the other one is a simple helper. I'll get to it soon
