### ISSUE TITLE
find unmapped lines? 

### ISSUE THREAD

**Issue by rpokrovskij** [microsoft/sourcemap-toolkit#65]
How this lib can be used to find unmapped lines (lines in source that are absent in sourcemap)? Just list some API members.

**Comment by christiango** [comment]
Can you provide some more details on the scenario? What is it that you are trying to do with the lines you find?

**Comment by rpokrovskij** [comment]
Thank you for your interest. 
I know that sourcemap usually doesn't cover whole webpack bundles (e.g. source-map-explorer reports that my bundles are not covered for 27%-7%). And I'm interesting to investigate what kind of bundle's code has no its cover in sourcemaps.  Create a small utility that can show me those lines. Just as an investigation instrument.

**Comment by christiango** [comment]
I haven't tried to do something like that myself, but you might be able derive the uncovered lines by using the source map object returned by SourceMapParser.ParseSourceMap. It has entries for the mappings in the source maps, so you'd just need to figure out how to determine which lines aren't covered by those mappings

**Comment by christiango** [comment]
Going to close this isssue since it hasn't been active in the past year and doesn't quite fall within the scope of this library
