### ISSUE TITLE
Switch to test-framework that allows tests to be run on linux

### ISSUE THREAD

**Issue by mdavidsen** [microsoft/sourcemap-toolkit#69]
The current test-framework used (Microsoft.VisualStudio.TestTools.UnitTesting) does not allow for tests to be run on linux. 

I did a test to see how much job it was to switch framework, and it was mostly a search & replace over the repo, removing a few decorators and doing asserts for expected exceptions. Is this something you'd be willing to accept a PR for?

**Comment by christiango** [comment]
Yes!
