### ISSUE TITLE
Can't find parameterless constructors for SourceMapProvider and SourceCodeProvider while trying to use 'Call Stack Deminification' snippet

### ISSUE THREAD

**Issue by kanybekov** [microsoft/sourcemap-toolkit#78]
Hello, everyone!
Just imported SourceMapToolkit package to my .net core project. 
Trying to use the snippet from https://github.com/microsoft/sourcemap-toolkit#usage-1

```
StackTraceDeminifier sourceMapCallstackDeminifier = StackTraceDeminfierFactory.GetStackTraceDeminfier(new SourceMapProvider(), new SourceCodeProvider());
DeminifyStackTraceResult deminifyStackTraceResult = sourceMapCallstackDeminifier.DeminifyStackTrace(callstack);
string deminifiedCallstack = deminifyStackTraceResult.ToString();
```

'using SourcemapToolkit.CallstackDeminifier;' was added to my code.

I see that no parameterless constructors are available for 'SourceMapProvider' and 'SourceCodeProvider'. Am I doing something wrong? Maybe I didn't notice some important thing? 

Any help will be appreciated.

**Comment by christiango** [comment]
Source code provider is something that is application specific, the expectation is that applications provide their own implementation of the interface

**Comment by christiango** [comment]
Closing this since this interface is expected to be provided by the hosting application.
