### ISSUE TITLE
Nuget version

### ISSUE THREAD

**Issue by mrWayer** [microsoft/sourcemap-toolkit#79]
The latest version of Nuget package does not contain toString actions in DeminifiedResult. Is anybody can deploy it?

**Comment by christiango** [comment]
Thanks for reaching out. Unfortunately our publishing pipeline is no longer working and we do not have any dedicated resources working on the project that can stand up a new publishing pipeline at this time. You can find more details in https://github.com/microsoft/sourcemap-toolkit/issues/64
